### ISSUE TITLE
Visions of N'zoth: Add new collectibles

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#147]
Roadmap:

- [x] Research: Do expedition items drop from the new vendor? (Moved to https://github.com/SacredDuckwhale/Rarity/issues/154)
- [x] Add new collectibles to the item DB
  - [x] Add rare drops to the item DB
  - [x] Add drops from the new raid (Moved to https://github.com/SacredDuckwhale/Rarity/issues/156)
  - [x] Potentially add vision drops as well (Moved to https://github.com/SacredDuckwhale/Rarity/issues/155)
- [x] Add relevant mapIDs to the DB
- [x] Add waypoint data for the new items (requires new mapIDs to be added first)
- [x] Defeat detection for rare drops
  - [x] Defeat detection for visions (if items are relevant) - Pointless, since there's no lockout
  - [x] Defeat detection for raid drops (Moved to https://github.com/SacredDuckwhale/Rarity/issues/156)
- [x] Categorize all rares correctly (group vs soloable)
- [x] Testing: Tracking & Defeat detection
  - [x] Test rare drops (see blow)
  - [x] Test raid drops (LFR) (Moved to https://github.com/SacredDuckwhale/Rarity/issues/156)
  - [x] Test vision tracking (if applicable) - Not applicable
- [ ] Update localization phrases
- [x] Update drop rates once more data is available (via https://github.com/SacredDuckwhale/Rarity/issues/74)
- [x] Update TOC version to 8.3 (Core + Options)

---

Mounts:

- [x] https://ptr.wowhead.com/item=174840/xinlao#comments
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174641/reins-of-the-drake-of-the-four-winds
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174769/malevolent-drone#comments
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174842/slightly-damp-pile-of-fur
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174752/ivory-cloud-serpent
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=173887/clutch-of-ha-li
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174841/rens-stalwart-hound
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174753/waste-marauder
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation

Pets:

- [x] https://ptr.wowhead.com/item=174473/kuddly#comments
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174456/bottle-of-gloop#comments (Moved to https://github.com/SacredDuckwhale/Rarity/issues/158)
- [x] https://ptr.wowhead.com/item=174476/black-chitinous-plate#comments
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174462/void-cocoon#comments (Skipping this because it's extremely easy to get, so hardly worth tracking)
- [x] https://ptr.wowhead.com/item=174474/corrupted-tentacle
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174475/stinky-sack#comments
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174478/wicked-lurker#teaches-ability ?
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation

Toys:

- [x] https://ptr.wowhead.com/item=175141
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=175142/all-seeing-right-eye
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=169303/hell-bent-bracers
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174874/budget-kthir-disguise
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174873/trans-mogu-rifier
  - [x] Testing: Defeat detection
  - [x] Testing: Waypoint creation

**Comment by SacredDuckwhale** [comment]
Finished in 7fc9365c45b394871be1c565cbc418ca9dc4a7ea.
