### ISSUE TITLE
Add tracking for collectibles dropped in Horrific Visions

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#155]
Mounts:

- [x] https://ptr.wowhead.com/item=174653/mail-muncher 

---

Pets:

- [x] https://ptr.wowhead.com/item=174458/void-scarred-hare
- [x] https://ptr.wowhead.com/item=174460/box-labeled-danger-void-rat-inside#comments
- [x] https://ptr.wowhead.com/item=173726/box-with-faintly-glowing-air-holes
- [x] https://ptr.wowhead.com/item=174461/swirling-black-bottle#comments
- [x] https://ptr.wowhead.com/item=174459/voidwoven-cat-collar#comments
- [x] https://ptr.wowhead.com/item=174646/void-link-frostwolf-collar#comments
- [x] https://ptr.wowhead.com/item=174457/cthuffer#comments

---

Toys:

- [x] https://ptr.wowhead.com/item=174926/overly-sensitive-void-spectacles#comments
- [x] https://ptr.wowhead.com/item=174924/void-touched-souvenir-totem#comments

**Comment by SacredDuckwhale** [comment]
Detection and items added in e6e48181f12dda857ed13b101e99099a56f4946d.

Can't test it really, as only one Vision is active each week and I haven't the time to clear all objectives right now. However, as the detection is encounter-based, I'm fairly confident it should be working.
