### ISSUE TITLE
Add tracking for collectibles dropped in the Ny'alotha raid

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#156]
Requires LFR to be released before it can be tested?

---

Roadmap:

- [x] Add items to the DB
- [x] Add defeat detection for the new items
- [x] Test tracking & defeat detection (LFR)

---

Pets:

- [x] https://ptr.wowhead.com/item=174452/eye-of-corruption#comments
  - [ ] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174447/void-scarred-anubisath#comments
  - [ ] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174448/aqir-hivespawn#comments
  - [ ] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174449/rakim
  - [ ] Testing: Defeat detection
  - [x] Testing: Waypoint creation
- [x] https://ptr.wowhead.com/item=174446/fractured-obsidian-claw#comments
  - [ ] Testing: Defeat detection
  - [x] Testing: Waypoint creation

**Comment by SacredDuckwhale** [comment]
Testing all raid difficulties isn't feasible, but otherwise I'll consider this done as of 6a53b394249766e91b88796a4c575adc7d6d7a22.
