### ISSUE TITLE
Add tracking for collectibles contained in 8.3 paragon caches

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#157]
- [ ] https://ptr.wowhead.com/item=174481/cursed-dune-watcher#battle-pet
  - [ ] Testing: Defeat detection
  - [ ] Testing: Waypoint creation
- [ ] https://ptr.wowhead.com/item=174479/jade-defender
  - [ ] Testing: Defeat detection
  - [ ] Testing: Waypoint creation

**Comment by SacredDuckwhale** [comment]
Added in 5cd5030caedbee6e90a483dad7077d4883004bb6.
