### ISSUE TITLE
Add tracking for Gloop (pet)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#158]
This is taking too much time due to the limited availability and various pools I'd need to hunt down, so I'm postponing it to push a release sooner.

---

Uldum:

* Malignant Gnasher School
* Aberrant Voidfin School
* Others TBD

Vale:

* TBD

---

Roadmap:

- [ ] https://ptr.wowhead.com/item=174456/bottle-of-gloop#comments
  - [ ] Testing: Defeat detection
  - [ ] Testing: Waypoint creation

**Comment by SacredDuckwhale** [comment]
Actually, I think the fishing schools are only available during these assaults, so it's easiest to add them and ignore the assault itself.
