### ISSUE TITLE
Add collectibles from the Shadowlands expansion

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#215]
This will be split into several parts:

- [x] Add items to the DB (https://github.com/SacredDuckwhale/Rarity/issues/216)
- [x] Add waypoint data and UiMapIDs (https://github.com/SacredDuckwhale/Rarity/issues/217)
- [x] Add defeat detection (quest IDs) (https://github.com/SacredDuckwhale/Rarity/issues/218)
- [ ] After some weeks: Adjust drop rates (need to wait for wowhead to collect some data)

**Comment by SacredDuckwhale** [comment]
This will have to do; most items seemed to have a semi-decent sample size on wowhead by now.
