### ISSUE TITLE
Work through new expansion checklist for BFA release

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#35]
Original: Allara's "NEW EXPANSION PACK - TO-DO LIST / CHEAT SHEET" (backup copy [here](https://gist.github.com/SacredDuckwhale/8b50bd0cfbbae8139344e3d6fce78f2f))

The list was then updated for BFA.

**Items:**
- [x] Reevaluate group sizes for all items (items from 2 expansions ago become soloable; items from last expansion become groups of 3) - Note: Only content <= 10 levels below the player uses Personal Loot in BFA
- [x] New mounts
- [x] New pets
- [x] New toys
- [ ] New 100% drop items - What is the point in tracking these, even if there were any? Skipped, for now.
- [x] Guaranteed mounts from bosses convert to non-guaranteed (don't forget to set wasGuaranteed = true): Will probably affect mounts from current Mythic raids only (Heroic mounts have been removed entirely since WOD when a new expansion launches)
- [x] New rare killing achievements (under the Exploration achievement tab, like: http://www.wowhead.com/achievements/character-achievements/exploration/15257-legion)
	
**Nodes and zones:**
- [x] Fishing nodes (GatherMate2/Constants.lua)
- [x] NO LONGER: New zones for Sea Turtle (http://wowpedia.org/MapID) (they stopped putting it in new expansions starting with Warlords of Draenor)
	
**APIs:**
- [x] Check if NPC ID format changed
- [x] Check if instance difficulty API or IDs changed
- [x] Check if COMBAT_LOG_EVENT_UNFILTERED changed
- [x] Check for other API changes (i.e. http://wowpedia.org/Patch_6.0.1/API_changes)
	
**Other:**
- [x] Good-luck coins (Bonus rolls)
- [x] New Archaeology races: /run for race_id = 1, GetNumArchaeologyRaces() do Rarity:Print("race_id: "..race_id.." | "..GetArchaeologyRaceInfo(race_id)) end
- [x] Add a new category icon for the expansion
- [x] If a new class was added, add it to the list at the top of Options.lua in the Options module
	
Optional:
- [x] Find a better category icon (original artwork would be great, but I haven't found one)
- [ ] Toy conversions: Are existing items being converted to toys and should be added to the addon? -> Skipped because I haven't found any. If any are being converted, they'll have to be added later.
- [ ] Mining nodes -> Skipped, for now. Allara. "There is no official support for user-added Mining or Herbalism items."

**Comment by SacredDuckwhale** [comment]
Here is the remaining tasks after adding a bunch of stuff already:

Arathi Warfront: #48
Island Expeditions: #49
World Events: #50
Mythic Dungeons: #51
Mythic Plus: #52
BOE Mounts: #53

Since it's a lot of different things coming together that should be tested and researched individually, I'll split this into separate issues.

**Comment by SacredDuckwhale** [comment]
Closing this as the world events are already split off and can be tackled later. All the other, basic BFA stuff should be included in the latest release.
