### ISSUE TITLE
Add tracking for the Pterrordax Egg

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#81]
https://www.wowhead.com/item=157782/pterrordax-egg

Should be relatively simple, I just haven't the time right now. Putting it here as a reminder primarily.

---

Roadmap:
- [x] Task: Add item to DB
- [ ] Research: Find a way to only track it for L50(+, presumably) Horde characters
- [ ] Task: Implement said restriction to prevent low level alts and Alliance characters from seeing it
- [ ] Research: Only show the tooltip if the player can actually loot it - similar to the skinning pet on Argus perhaps?
- [ ] Task: Add the tooltip functionality (I believe I already added a custom tooltip handler back in the day that could be used...)
- [x] Testing: Make sure the item is tracked for Horde characters of the appropriate level
- [ ] Testing: Make sure the item is NOT tracked NOR shown for low level/Alliance characters

**Comment by SacredDuckwhale** [comment]
https://www.wowhead.com/quest=50393/a-child-of-paku#comments

**Comment by SacredDuckwhale** [comment]
Not sure if the level restrictions apply, so I'll just leave out that part. It's quite possible the item could be looted but the quest couldn't be started before level 50. I really have no idea, but I doubt it matters much.

Alliance characters are filtered automatically if using the ``requiresHorde`` flag.

**Comment by SacredDuckwhale** [comment]
Added tracking in bd57c51fa3052163989f9759e224b0228e49130d. If anything else needs doing, I'll have to revisit this issue.
