### ISSUE TITLE
Add support for appearance tracking

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#95]
Since users have tried to fiddle with the Custom items in order to do this manually, a more streamlined way would be useful. It's merely an idea, but I think working with AllTheThings to temporarily add missing appearances while farming legacy content could be somewhat simple to add. This would save a lot of hassle and hopefully integrate seamlessly with Rarity if done correctly.

Considerations:
- [ ] Research: Does ATT offer a simple API that Rarity could use for this?
- [ ] Research: Will Rarity's tracking of attempts, times, etc. add unnecessary bloat?
- [ ] Task: It should probably be disabled for appearances, since they're tracked only temporarily
- [ ] Feature: Add temporary tracking of items
- [ ] Feature: Add detection for appearances (since the items should be set to tracked only if the appearance isn't known)
- [ ] Improvement: Extend config GUI to show the currently tracked appearance items (in a new tab?)
